#!/bin/sh
# the first argument must be the name of the experiment
# the second argument must be the cuda number 
# the third argument must be the number of pretrained steps to start
# fourth argument for train_steps

mkdir $1 

if [ $# -lt 3 ]
    then 
        nohup python train.py -data data/demo -save_model $1/demo-model -gpuid $2 -tensorboard -tensorboard_log_dir $1 -seed 3435 -train_steps 10000 -valid_steps 800 -warmup_steps 800 -report_every 50 -decoder_type transformer -encoder_type transformer -word_vec_size 512 -rnn_size 512 -layers 6 -transformer_ff 2048 -heads 8 -accum_count 8 -optim adam -adam_beta1 0.9 -adam_beta2 0.998 -decay_method noam -learning_rate 2.0 -max_grad_norm 0.0 -batch_size 4096 -batch_type tokens -normalization tokens -dropout 0.1 -label_smoothing 0.1 -max_generator_batches 2 -param_init 0.0 -param_init_glorot -position_encoding > $1/nohup.out &
else
        nohup python train.py -data data/demo -save_model $1/demo-model -gpuid $2 -train_from $3 -train_steps $4 > $1/nohup.out &
fi
